### ISSUE TITLE
standardinit_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Ichag** [andig/beats4pi#6]
I'm sorry, I have nothing more as output. Does someone have any idea why is error occures on the following command? 
I'm running it on a raspberry pi 3. 
Docker version is 18.09.0.

```bash
docker run -v $(pwd):/build -e BEATS_VERSION=6.1.1 andig/beats4pi
```

**Comment by andig** [comment]
Seems I may have broken the arm build in https://github.com/andig/beats4pi/commit/b92949db3a35a9ad51d1d5d14abebdb39a92f151. Need to double-check why the build doesn‘t seem to create an arm binary although target architecture is set.

**Comment by andig** [comment]
Mhm, not sure what you're doing. I've just:

- built according to readme
- copied to raspi and extracted
- ran:

      pi@server:~/filebeat-6.6.1-linux-x86 $ ./filebeat  --help
      Usage:
      filebeat [flags]
      filebeat [command]

**Comment by andig** [comment]
@Ichag I've just realized what's going on:

> I'm running it on a raspberry pi 3.

The tagged image is for linux and doesn't support multi-arch. To run the build on the pi itself you'll simply have to build the docker image, too. See readme for how to.
